// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-HiPPSAwv2mH9lyXZ1Wb9s3tEwyx3vpM',
    appId: '1:503308158259:web:1f4382071d3be0b8772a46',
    messagingSenderId: '503308158259',
    projectId: 'xguard-app22',
    authDomain: 'xguard-app22.firebaseapp.com',
    storageBucket: 'xguard-app22.appspot.com',
    measurementId: 'G-DEW6CDHW51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vHF9DvbmaxsUWqd-4iDi7FjNCecS-Kk',
    appId: '1:503308158259:android:3852a9035aba0171772a46',
    messagingSenderId: '503308158259',
    projectId: 'xguard-app22',
    storageBucket: 'xguard-app22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--RiLKPOlzx9aa4hWa5REIdoi482sOrs',
    appId: '1:503308158259:ios:351f4937fc172fb6772a46',
    messagingSenderId: '503308158259',
    projectId: 'xguard-app22',
    storageBucket: 'xguard-app22.appspot.com',
    iosClientId: '503308158259-b2koqai9j3me4e9em4nsa9l8du0a96fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.xguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--RiLKPOlzx9aa4hWa5REIdoi482sOrs',
    appId: '1:503308158259:ios:351f4937fc172fb6772a46',
    messagingSenderId: '503308158259',
    projectId: 'xguard-app22',
    storageBucket: 'xguard-app22.appspot.com',
    iosClientId: '503308158259-b2koqai9j3me4e9em4nsa9l8du0a96fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.xguard',
  );
}
